version: "3.9"

services:
  web:
    container_name: ecommtool_web
    build:
      context: .
      dockerfile: src/docker/Dockerfile
    image: kamalesh1512/ecommtool_web:latest
    ports:
      - "127.0.0.1:3000:3000"  # bind to localhost (good if using Nginx reverse proxy)
    restart: always
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      NEXTAUTH_SECRET: XtHlYn1lUpw9c8Wc+yzCj7ft/9mkinUwI1pDyUM8F/M=
      NEXTAUTH_URL: 
    command: ["npm", "run", "start"]
